#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap           12

bspc config focused_border_color \#707880

bspc config left_padding	 0
bspc config right_padding	 0
bspc config top_padding		 36

bspc config split_ratio          0.55

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_side

# Autostart

sxhkd &

feh --bg-fill --no-fehbg ~/Pictures/wallhaven-x6jy1v.png &

$HOME/.config/polybar/launch.sh

picom --config "$HOME"/.config/picom/picom.conf &

